name: coordinator
version: 0.1.1
repository: https://github.com/nogipx/coordinator
issue_tracker: https://github.com/nogipx/coordinator/issues
description: Application Coordinator pattern for Flutter. 
  Architecture pattern for decoupling app behavior.

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  collection: ^1.17.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
